nelmio_api_doc:
  documentation:
    servers:
      - url: http://localhost:8000/
        description: API over HTTP
    info:
      title: Restesso ☕
      description: Restesso est une API réalisée dans le cadre d'une formation API à Ynov. Elle tourne autour du café, de ses catégories, des types et différents grains de cafés.
      version: 1.0.0
    paths:
      /api/v1/login_check:
        post:
          operationId: postCredentialsItem
          tags:
            - Token
          summary: Permet d'obtenir le JWT pour s'authentifier ainsi qu'un refresh token.
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - uuid
                    - password
                  properties:
                    username:
                      type: string
                      example: "admin"
                    password:
                      type: string
                      example: "password"
          responses:
            "200":
              description: Fournit un JWT et un refresh token.
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      token:
                        type: string
                        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                      refresh_token:
                        type: string
                        example: "67abf20ff7833531980b380f08b7e44876857376dd6256d..."
    components:
      schemas:
        User:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            username:
              type: string
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []
  areas:
    path_patterns:
      - ^/api/v1(?!/doc$)